spring:
  application:
    name: chat-service

  datasource:
    url: jdbc:mysql://localhost:3308/chat_service
    username: service_user
    password: service_user
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: bf771e0458627054cd16c85be1038e3f
            client-secret: fncw2rVSWBMzGY1YAvqGR0RvFx5VDSiI
            scope:
              - profile_nickname
              - account_email
              - name
              - gender
              - phone_number
              - birthday
              - birthyear

            redirect-uri: "http://localhost:8089/login/oauth2/code/kakao"
            client-name: kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
server:
  port: 8089
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true



